# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Virtha-Events plugin compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./virtha-events
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '22'
    - run: mkdir /home/runner/work/VIRTHA-Events/VIRTHA-Events/compiled
    - run: mvn package -f pom.xml

    - name: Obtener nombre del JAR
      id: get_jar_name
      run: |
          JAR_NAME=$(ls target/*.jar | xargs -n1 basename)
          echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV
          echo "::set-output name=jar_name::${JAR_NAME}"
    
    - name: Generate a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{ env.JAR_NAME }}  # Usa el nombre del JAR
        path: target/${{ env.JAR_NAME }}  # Ruta del archivo
          
  generate-jar:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.9
      with:
        path: /home/runner/work/VIRTHA-Events/VIRTHA-Events/compiled
