# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Virtha-Events plugin compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./virtha-events
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '22'
    - name: Crear directorio de dependencias
      run: mkdir -p src/main/dependencies
    - name: Descargar EternalTags.jar
      run: |
        # Descargar EternalTags.jar desde GitHub Releases
        mkdir -p src/main/dependencies
        curl -L -o src/main/dependencies/EternalTags.jar https://github.com/Oribuin/EternalTags/releases/download/1.3.2/EternalTags-1.3.2.jar
    - run: mvn package -f pom.xml

    - name: Generate plugin artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: "virtha-events-1.0-bukkit.jar"
        path: "/home/runner/work/VIRTHA-Events/VIRTHA-Events/virtha-events/target/virtha-events-1.0-bukkit-shaded.jar"
